/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/planet/scene.gltf --transform --simplify 
Files: public/planet/scene.gltf [10.23KB] > C:\Users\karti\OneDrive\Desktop\kartikdotdev_newPortfolio\oldwebsite\Kartik-Portfolio\scene-transformed.glb [301.84KB] (-2851%)
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode" rotation={[0.031, 0, 0.064]}>
          <group name="Clouds_1">
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Clouds} />
          </group>
          <group name="Planet_2">
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Planet} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
